export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const GET_FAVORITE_PRODUCTS_REQUEST = "GET_FAVORITE_PRODUCTS_REQUEST";
export const GET_FAVORITE_PRODUCTS_SUCCESS = "GET_FAVORITE_PRODUCTS_SUCCESS";
export const GET_FAVORITE_PRODUCTS_FAIL = "GET_FAVORITE_PRODUCTS_FAIL";
